// Content sourced from the AMG Venture Partners PDF brief.

export const NAV_LINKS = [
  { label: 'Home', to: '/' },
  { label: 'Founder Services', to: '/founder-services' },
 // { label: 'Pricing', to: '/pricing' },
  { label: 'Resources', to: '/resources' },
  { label: 'Contact', to: '/contact' },
  {label:'About Us', to: '/about'},
  // {label:'Investment Readiness Program', to: '/investment-readiness-program'},
];

export const HERO = {
  eyebrowTags: ['Pre-Seed', 'Seed', 'Series A'],
  title: 'Raise Capital With Conviction.',
  description:
    'AMG Venture Partners equips founders, incubators, and accelerators across North America and Europe with the strategic clarity, tools, and connections to close their rounds.',
  primaryCta: { label: 'Explore Services', to: '/founder-services' },
  secondaryCta: { label: 'Book a Consultation', to: '/contact' },
};

export const WHO_WE_ARE = {
  eyebrow: 'Who We Are',
  title: 'Practical Insight. Real Results.',
  paragraphs: [
    'AMG Venture Partners was founded by operators and investors who have lived on both sides of the table. We provide the exact frameworks, documents, and introductions that move fundraising processes forward.',
    'Whether you are a first-time founder or an accelerator looking to elevate your entire cohort, we meet you where you are and build toward where you need to be.',
  ],
  bullets: [
    'Hands-on, founder-first methodology',
    'Deep North American & European investor networks',
    'Stage-appropriate advice from pre-seed to Series A',
  ],
  stat: { label: 'Avg. Time to First Term Sheet', value: '8–12 Weeks' },
  image:
    'https://images.unsplash.com/photo-1680459575585-390ed5cfcae0?crop=entropy&cs=srgb&fm=jpg&ixid=M3w4NTYxOTB8MHwxfHNlYXJjaHwzfHxzdGFydHVwJTIwZm91bmRlcnMlMjBjb2xsYWJvcmF0aXZlfGVufDB8fHx8MTc3NzI4NTI0OXww&ixlib=rb-4.1.0&q=85',
};

export const SERVICE_PILLARS = [
  { title: 'Financial Models', desc: 'Investor-grade.', accent: 'yellow' },
  { title: 'Pitch Decks', desc: 'Compelling narratives.', accent: 'turquoise' },
  { title: 'Investor Network', desc: 'Across North America & Europe.', accent: 'teal' },
  { title: 'Valuation', desc: 'Defensible analysis.', accent: 'yellow' },
];

export const FOUNDER_SERVICES_INTRO = {
  eyebrow: 'For Founders',
  title: 'Founder Services',
  description:
    'From your first pitch deck to your closing round, AMG Venture Partners provides hands-on, stage-appropriate support at every critical step of the fundraising journey. Each service is tailored to your specific context — your stage, sector, geography, and target investor.',
};

export const NOT_SURE_CTA = {
  eyebrow: 'Not Sure Where to Start?',
  title: 'Schedule a Free Consultation',
  description:
    "Book a free strategy call and we'll map the right service path for your current stage and fundraising journey.",
  cta: { label: 'Book a Free Strategy Call', to: '/contact' },
  note: 'No obligation. 30 minutes. All new engagements start here.',
};

export const PRICING_INTRO = {
  eyebrow: 'Pricing',
  title: 'Transparent, Flat-Fee Pricing',
  description:
    'No hourly surprises. Every engagement is scoped, priced, and agreed upon before we start.',
};

export const HOW_WE_WORK_INTRO = {
  eyebrow: 'How We Work Together',
  description:
    'A structured engagement designed to be efficient, collaborative, and output-driven — no bureaucracy, no back-and-forth chaos.',
};

const STANDARD_PRICING_NOTE = {
  eyebrow: 'Pricing',
  title: 'Transparent, Flat-Fee Pricing',
  description: 'No hourly surprises. Every engagement is scoped, priced, and agreed upon before we start.',
};

const PITCH_DECK_REVIEW_PRICING = [
  {
    tier: 'Written Review',
    price: '$650',
    sub: 'Async written feedback you can action and self-direct revisions from.',
    popular: false,
    features: [
      'Slide-by-slide annotated feedback',
      'Red & green flag analysis',
      'Market and competitive assessment',
      'Written summary report',
      'Metrics follow-up call',
    ],
    cta: 'Get Started',
  },
  {
    tier: 'Full Review + Expert',
    price: '$1,100',
    sub: 'The complete review experience — written analysis plus a live 60-minute session to align on your revision roadmap.',
    popular: true,
    features: [
      'Everything in Written Review',
      'Investor Q&A anticipation notes',
      'Traction and team section deep dive',
      '60-min live debrief call',
      'Revision prioritisation roadmap',
      '14-day post-debrief email Q&A',
    ],
    cta: 'Get Started',
  },
  {
    tier: 'Concierge Review',
    price: 'Custom',
    sub: 'For founders who want an active, senior day-to-day co-pilot on investment readiness and fundraising readiness.',
    popular: false,
    features: [
      'Structured evaluation calls',
      'Iterative pricing (per deck)',
      'Current-raise competitive insights',
      'Dedicated founder debrief sessions',
      'Demo day presentation recommendation',
      'Dedicated account coordinator',
    ],
    cta: 'Get Started',
  },
];

const PITCH_DECK_REVIEW_INCLUDES = [
  'Intake questionnaire and context review',
  'Slide-by-slide annotated feedback (every slide)',
  'Narrative flow and story arc assessment',
  'Market sizing logic and credibility review',
  'Competitive landscape framing analysis',
  'Traction and proof-point strength assessment',
  'Team narrative review',
  'Financial slide and ask review',
  'Red flag identification (investor deal-breakers)',
  'Investor Q&A anticipation notes (likely questions from your deck)',
  'Executive summary, top 3 strengths and top 3 critical improvements',
  '80-min live debrief call with walkthrough',
  'Post-call email with revision prioritisation list',
];

export const SERVICES = [
  {
    slug: 'pitch-deck-review',
    title: 'Pitch Deck Review',
    tagline: 'Sharpen your story before you step into the room.',
    accent: 'yellow',
    why: 'A meticulous, investor-perspective critique of your existing pitch deck — designed to identify narrative gaps, structural weaknesses, and missed opportunities before they cost you a term sheet.',
    whyHeading: 'Most rejections happen because of how a story is told — not the business behind it.',
    whyPoints: [
      {
        title: 'Vague Feedback Is Useless',
        text: 'Most peer review gives polite, surface-level validation. What you actually need is a hard, investor-perspective critique — exactly what is unclear, what is unconvincing, and what is missing.',
      },
      {
        title: "You Can't See Your Own Blind Spots",
        text: 'You know your business too well. The assumptions, jumps, and shortcuts that feel obvious to you are exactly what confuses an investor reading your deck for the first time.',
      },
      {
        title: 'One Weak Slide Can Kill the Whole Deck',
        text: 'A single confusing slide, an unclear chart, or a missing proof point can derail an otherwise strong narrative. These gaps need to be caught before investors do.',
      },
    ],
     pricing: PITCH_DECK_REVIEW_PRICING,
    whatsIncluded: PITCH_DECK_REVIEW_INCLUDES,
    deliverHeading: 'Investor-grade feedback that tells you exactly what to fix and why.',
    deliver: [
      { title: 'Slide-by-Slide Annotation', text: 'Every slide reviewed with detailed written annotations on copy, structure, evidence, and visual clarity.' },
      { title: 'Narrative Flow Analysis', text: 'Does your story compound, or fragment? We map the logical arc and flag where investor attention drops.' },
      { title: 'Market & Story Review', text: 'Pressure-test your market sizing, segmentation, and category framing for institutional credibility.' },
      { title: 'Red Flag Identification', text: 'We surface the questions a sophisticated investor will ask — before you walk into the room.' },
      { title: 'Investor Q&A Anticipation', text: 'A list of the toughest questions your deck will trigger, with suggested answers and supporting data.' },
      { title: 'Competitive & Team Review', text: 'Sharpen positioning against alternatives and stress-test how your team slide reads to investors.' },
    ],
    process: [
      { step: 'Intake & Context Setting', day: 'Day 1', text: 'You share your deck, target investor profile, and round context. We align on focus areas.' },
      { step: 'Deep Deck Analysis', day: 'Day 1–4', text: 'A senior partner reviews your deck slide-by-slide against an institutional evaluation framework.' },
      { step: 'Written Feedback Report', day: 'Day 5', text: 'You receive a written report with key strengths, critical gaps, and prioritised recommendations.' },
      { step: 'Live Debrief Session', day: 'Day 6', text: 'A 60-minute working session — discussing each finding, answering your questions, and creating a revision outline.' },
    ],
    pricingNote: STANDARD_PRICING_NOTE,
    finalCta: {
      title: 'Ready to Strengthen Your Deck?',
      description: 'Submit your deck and get a full investor-perspective review back within 5 business days.',
      cta: { label: 'Get Started', to: '/contact' },
    },
    faqs: [
      { q: 'How quickly can you turn around the review?', a: 'Standard turnaround is 5 business days from receipt of materials. Rush 48-hour turnaround is available for an additional fee.' },
      { q: 'Is this feedback from someone who has actually sat on the investor side?', a: 'Yes. Reviews are conducted by partners who have evaluated hundreds of decks from the investor seat — not generalist consultants.' },
      { q: 'Do you sign NDAs?', a: 'Mutual NDAs are standard for every engagement. Your deck and information are never shared.' },
      { q: 'Will you also help me rewrite the deck?', a: 'The review focuses on critique and recommendations. If you want hands-on rebuilding, our Pitch Deck Creation service is the right next step.' },
    ],
  },
  {
    slug: 'pitch-deck-creation',
    title: 'Pitch Deck Creation',
    tagline: 'Your story, told with clarity and conviction.',
    accent: 'turquoise',
    why: 'We build investor-grade pitch decks from the ground up — crafting the narrative architecture, structuring each slide for maximum impact, and delivering a polished presentation that opens doors and moves investors to act.',
    whyHeading: 'Most pitch decks fail before a founder ever steps into the room.',
    pricing: [
      {
        tier: 'Startup & Copy',
        price: '$1,800',
        sub: 'For founders who need the story structured and the slides written — design not included.',
        popular: false,
        features: [
          'Founder discovery session',
          'Narrative architecture doc',
          'Slide-by-slide copy writing',
          'Investor-tailored messaging',
          '2 revision rounds',
          'File delivery (editable)',
        ],
        cta: 'Get Started',
      },
      {
        tier: 'Full Deck',
        price: '$3,500',
        sub: 'The complete pitch deck experience — story, copy, design, and presentation coaching.',
        popular: true,
        features: [
          'Everything in Startup & Copy',
          'Custom slide visualisations and brand',
          'Market sizing and competitive landscape',
          'You full rounds of revision based on your feedback',
          'Editable PowerPoint file (fully yours to update)',
          'Live walkthrough session (60 min)',
        ],
        cta: 'Get Started',
      },
      {
        tier: 'Concierge / Custom',
        price: 'Custom',
        sub: 'For founders building to raise across multiple rounds, access to our senior advisory network.',
        popular: false,
        features: [
          'Iterative pricing',
          'Unlimited revisions (per deck)',
          'Current-raise competitive insights',
          'Senior day-to-day advisory',
          'Demo day presentation coaching',
          'Dedicated account coordinator',
        ],
        cta: 'Get Started',
      },
    ],
    whatsIncluded: [
      'Full 90-min investor discovery session',
      'Slide-by-slide copy and messaging development',
      'Narrative one-page pitch outline',
      'Presentation-ready PDF export',
      'We conduct founder discovery sessions',
      'Custom slide visualisations and brand elements',
      'Market sizing and competitive landscape framing',
      'You full rounds of revision based on your feedback',
      'Narrative architecture across your story',
      'Investor profile messaging customisation',
      'Editable PowerPoint file (fully yours to update)',
      'Live walkthrough session (60 min)',
    ],
    whyPoints: [
      {
        title: 'You Have 3 Minutes to Make an Impression',
        text: 'Investors form a first impression within the first three slides. Without a tight narrative arc, the rest of the deck rarely gets a fair read.',
      },
      {
        title: 'Insider Jargon Loses the Room',
        text: "What is obvious to a founder is often opaque to an investor outside your sector. Clarity beats sophistication in every fundraise.",
      },
      {
        title: 'Design Without Narrative Is Decoration',
        text: 'Beautiful slides without a sharp story do not raise rounds. Story-first design is the only design that converts.',
      },
    ],
    deliverHeading: 'A purpose-built pitch deck that tells your story with precision.',
    deliver: [
      { title: 'Narrative Architecture', text: 'A logical, progressive story arc designed to answer investor questions before they arise.' },
      { title: 'Slide-by-Slide Development', text: 'Each slide written, edited, and designed with copy, data visualisation, and visual hierarchy optimised for investor consumption.' },
      { title: 'Market & Competitive Framing', text: 'Clear market sizing, competitive differentiation, and category framing that positions your company in a context investors understand.' },
      { title: 'Investor-Tailored Messaging', text: "Messaging tailored to your target investor profile — fund focus, thesis, portfolio fit — so the pitch resonates with the right audience." },
      { title: 'Traction Storytelling', text: 'We translate your traction data into compelling proof points that signal momentum and de-risk the investment.' },
      { title: 'Editable Deliverables', text: 'Final deck delivered as PDF and editable PowerPoint — fully yours to update and adapt.' },
    ],
    process: [
      { step: 'Founder Discovery Session', day: 'Day 1', text: 'A 90-minute working session to extract your real story, traction, and the proof points investors need to see.', output: 'Preparation notes and specific question framework' },
      { step: 'Narrative Architecture', day: 'Day 2–7', text: 'We map the slide-by-slide flow and write a narrative document that locks the story before any design work begins.', output: 'Slide-by-slide narrative outline' },
      { step: 'First Draft Development', day: 'Day 8–12', text: 'We develop the full story: copy, charts, data visualisation, and visual design. Every slide is created for investor comprehension and decision making.', output: 'Slides first and 2th Revision' },
      { step: 'Revision Rounds', day: 'Day 13–18', text: 'You provide structured feedback on our first revision, discussing the clear narrative, ensuring the deck tells a compelling story.' },
      { step: 'Final Delivery & Walkthrough', day: 'Day 19', text: 'Final deck delivered as PDF and editable PowerPoint. All presentations ready to use, all slides created and without technical bugs.', output: 'Final deck + standalone coaching session' },
    ],
    pricingNote: STANDARD_PRICING_NOTE,
    finalCta: {
      title: 'Ready to Build a Deck That Converts?',
      description: 'Start with a free 30-minute consultation. We will map the right scope and timeline for your raise.',
      cta: { label: 'Get Started', to: '/contact' },
    },
    faqs: [
      { q: 'How long does the engagement take?', a: 'Typical timeline is 3–4 weeks from discovery session to final deck delivery, with two structured revision rounds built in.' },
      { q: 'Who actually writes the slides?', a: 'A senior partner leads the narrative and copy work. You co-create the story — no junior consultants doing the thinking.' },
      { q: 'Do you handle visual design too?', a: 'Yes. Every engagement includes polished, investor-ready visual design as a core deliverable.' },
      { q: 'Can I update the deck later?', a: 'Yes. You receive the editable PowerPoint file — fully yours to update for follow-on conversations and future rounds.' },
    ],
  },
  {
    slug: 'financial-model',
    title: 'Financial Model',
    tagline: 'Numbers that tell a story investors trust.',
    accent: 'teal',
    why: 'We build rigorous, investor-grade financial models from scratch — structured around how your business actually operates, with explicit assumptions investors can interrogate and scenarios that hold up under diligence.',
    whyHeading: 'Investors trust the model that survives scrutiny — not the spreadsheet that hides it.',
    pricing: [
      {
        tier: 'Starter',
        price: '$1,500',
        sub: 'For pre-revenue founders who need a clean model to anchor their raise.',
        popular: false,
        features: [
          '3-statement integrated model',
          'Driver-based revenue model',
          'Basic unit economics',
          'KPI summary dashboard',
          '2 revision rounds',
          'Live walkthrough session',
        ],
        cta: 'Get Started',
      },
      {
        tier: 'Full Model',
        price: '$2,800',
        sub: 'The complete financial model experience — bottom-up build, investor-grade unit economics, and a live debrief for due diligence.',
        popular: true,
        features: [
          'Everything in Starter',
          'Driver-based cohort and unit analysis',
          'Scenario analysis dashboard',
          'Sensitivity analysis dashboard',
          'Investor-profile scenario modelling',
          'Flat model review',
          'Live model walkthrough session',
          '30-day post-debrief email support',
        ],
        cta: 'Get Started',
      },
      {
        tier: 'Enterprise',
        price: 'Custom',
        sub: 'For complex businesses, multi-product scenarios, or those raising to institutional investors.',
        popular: false,
        features: [
          'Anything in Starter',
          'Multi-product / segment modelling',
          'Investor debt add-ins',
          'Ongoing model maintenance',
          'Board reporting support',
          'Priority turnaround',
        ],
        cta: 'Get Started',
      },
    ],
    whatsIncluded: [
      'Fully integrated 3-statement model (P&L, balance sheet, cash flow)',
      'Unit economics: LTV/CAC, payback period, gross margin by cohort',
      'Sensitivity analysis on key revenue and cost drivers',
      'Live model walkthrough session (60 min)',
      'Driver-based revenue model with your actual growth mechanics',
      'Base, best and worst case scenario analysis with driver toggles',
      'Capex requirements and fundraising schedule modelling',
      'Update support through closure (60 days)',
      'Hiring plan and headcount build (by role and timing)',
      'Executive-level 1-through summary (your profitability)',
      '30-day post-delivery Q&A support (email)',
    ],
    whyPoints: [
      {
        title: 'Top-Down Forecasts Get Ignored',
        text: 'Serious investors discount any forecast that is not built bottom-up from real operating drivers. A top-down model signals you have not thought through the business.',
      },
      {
        title: 'Errors Destroy Credibility Instantly',
        text: 'A single broken formula or implausible assumption can collapse an investor\u2019s confidence in the entire round. Models must be auditable, end to end.',
      },
      {
        title: 'Weak Unit Economics Kill the Round',
        text: 'If your contribution margin, payback, or LTV/CAC do not stand up to interrogation, no amount of narrative will fix it. Numbers must defend themselves.',
      },
    ],
    deliverHeading: 'A bottom-up, driver-based model engineered for institutional diligence.',
    deliver: [
      { title: '5-Year P&L, Cash Flow & Balance Sheet', text: 'Three integrated statements that tie back to a single set of explicit assumptions.' },
      { title: 'Driver-Based Revenue Build', text: 'Revenue modelled from the operating drivers that actually move your business — not a top-down growth percentage.' },
      { title: 'Cohort & Unit Economics Module', text: 'Cohort retention, contribution margin, payback, and LTV/CAC structured the way institutional investors expect to see them.' },
      { title: 'Hiring Plan & Runway Calculator', text: 'Headcount and burn modelled month-by-month with a clear view on cash runway across scenarios.' },
      { title: 'Scenario Toggles', text: 'Base, upside and downside scenarios driven by the same assumption sheet — no parallel models, no inconsistencies.' },
      { title: 'Investor Summary Page', text: 'A clean one-page summary of the model designed to slot directly into your deck or data room.' },
    ],
    process: [
      { step: 'Business Model Deep Dive', day: 'Day 1–2', text: 'We map your business drivers, pricing mechanics, acquisition channels, and cost structure to ensure the model reflects how your business actually works.', output: 'Driver mapping and model architecture doc' },
      { step: 'Model Architecture & Build', day: 'Day 3–7', text: 'We construct the full bottom-up model with all supporting schedules, revenue build, unit costs, capex, headcount, and financing assumptions.', output: 'Working and functional model' },
      { step: 'Scenario Analysis', day: 'Day 8–12', text: 'We build best, base, and worst-case scenarios tied to specific operating levers — pricing, volume, growth assumptions.', output: 'Scenario toggle dashboard' },
      { step: 'Review & Refinement', day: 'Day 13–14', text: 'We review the model with you, discussion assumptions and any needed refinements. Test edge-cases, validate logic.', output: 'Final refined model review' },
      { step: 'Walkthrough & Handoff', day: 'Day 15–16', text: 'Final live walkthrough of all model assumptions so you can speak to every number in investor meetings. Full handoff with documentation.', output: 'Model handover documentation and commentary' },
    ],
    pricingNote: STANDARD_PRICING_NOTE,
    finalCta: {
      title: 'Ready for an Investor-Grade Model?',
      description: 'Book a 30-minute scoping call. We will define the right model depth for your stage and round size.',
      cta: { label: 'Get Started', to: '/contact' },
    },
    faqs: [
      { q: 'Excel or Google Sheets?', a: 'Either — your preference. The model is fully editable and auditable in either format.' },
      { q: 'Can investors actually audit the assumptions?', a: 'Yes. Every assumption is explicit, sourced where relevant, and traceable through the model.' },
      { q: 'How long does it take?', a: '3–4 weeks for a full build, depending on business complexity. Faster turnarounds available for straightforward businesses.' },
      { q: 'Do you update the model after a raise?', a: 'Many founders engage us for a quarterly refresh after the round closes. The handoff model is yours to maintain in-house if you prefer.' },
    ],
  },
  {
    slug: 'valuation',
    title: 'Valuation',
    tagline: 'Know your worth and defend it.',
    accent: 'yellow',
    why: 'Defensible, market-grounded valuation analyses using the methodologies that institutional investors apply — comparable companies, precedent transactions, and DCF — calibrated to your stage, sector, and geography.',
    whyHeading: 'Valuation is where dollars are won and lost before term sheets are signed.',
    pricing: [
      {
        tier: 'Benchmarked Valuation',
        price: '$1,200',
        sub: 'A market-calibrated valuation range for founders calling the strategy for their next raise.',
        popular: false,
        features: [
          'Comparable company analysis',
          'Pre-money valuation range with written rationale',
          'DCF model (where applicable)',
          'Stage and sector benchmarks',
          'Negotiation talking points',
          '60-min results walkthrough',
        ],
        cta: 'Get Started',
      },
      {
        tier: 'Full Valuation',
        price: '$2,200',
        sub: 'The complete analysis for founders actively negotiating or preparing for institutional due diligence.',
        popular: true,
        features: [
          'Everything in Benchmarked Valuation',
          'Precedent transaction analysis',
          'DCF model (where applicable)',
          'Investor M&A-style analysis',
          'Dilution negotiation services',
          'Investor preparation services',
          'Investor prep Q&A support',
          '60-min live debrief session',
        ],
        cta: 'Get Started',
      },
      {
        tier: 'M&A + Board Delivery',
        price: 'Custom',
        sub: 'For complex situations: M&A, secondary sales, pre-IPO readiness, or board-level valuation review.',
        popular: false,
        features: [
          'Full M&A situation analysis',
          'Board-level presentation',
          'Investor debt scenarios',
          'Board / investor roadshow coaching',
          'Ongoing strategy support',
          'Priority turnaround',
        ],
        cta: 'Get Started',
      },
    ],
    whatsIncluded: [
      'Comparable company analysis (minimum 5 peer companies)',
      'Precedent transaction analysis from your sector and stage',
      'Pre-money valuation range with written rationale',
      'Growth-adjusted and stage-appropriate multiples',
      'Stage and sector benchmarks',
      'Post-round cap table modelling and dilution analysis',
      'Option pool analysis and how employee compensation analysis',
      'Investor M&A-style scenario analysis (at multiple multiples)',
      'Written valuation narrative for investor conversations',
      'Negotiation talking points and position defence',
      'NR / investor scenario modelling and results walkthrough',
      'NR-minute strategy session and results walkthrough',
    ],
    whyPoints: [
      {
        title: 'Founders Anchor on Hope, Not Evidence',
        text: 'Pricing your round on aspiration rather than analysis loses you both the deal and the trust of the investor. Defensibility is everything.',
      },
      {
        title: 'Mispricing Kills Deals Quietly',
        text: 'Anchor too high and investors walk away without explaining why. Anchor too low and you give away the company. Both are recoverable only with a defensible number.',
      },
      {
        title: 'Investors Test Your Number — Are You Ready?',
        text: 'Every serious investor will probe your valuation. The founders who close at strong numbers are the ones who can defend each one.',
      },
    ],
    deliverHeading: 'A defensible valuation built on real market data — not optimism.',
    deliver: [
      { title: 'Comparable Companies Analysis', text: 'A trading-comps screen using the right comp set, time window, and valuation multiples for your stage and sector.' },
      { title: 'Precedent Transactions Screen', text: 'M&A and financing precedents that establish a defensible valuation range based on what investors have actually paid.' },
      { title: 'DCF With Sensitivities', text: 'A discounted cash flow model with explicit assumptions and full sensitivity tables — no black-box outputs.' },
      { title: 'Pre-Money / Post-Money Waterfall', text: 'A clear cap-table waterfall showing dilution, ownership, and the implications of different round structures.' },
      { title: 'Investor-Facing Valuation Memo', text: 'A concise written memo summarising methodology, key assumptions, and the defensible valuation range — built to be shared with investors.' },
      { title: 'Founder Defense Playbook', text: 'A prep document with the toughest valuation questions investors will ask — and the data-backed answers to defend your number.' },
    ],
    process: [
      { step: 'Business & Market Context', day: 'Day 1–2', text: 'We collect your financials, contracts, market context, and fundraising goals. We identify your comparable set and benchmark your business against sector peers.', output: 'Benchmark dataset and selected comparables universe' },
      { step: 'Comparable Analysis', day: 'Day 3–5', text: 'We pull the comparable public set, M&A dataset, and growth-adjusted benchmarks. We standardise metrics and remove irrelevant outliers for the current investor stage.', output: 'Comparable investor universe and comparable companies' },
      { step: 'Valuation Modelling', day: 'Day 6–8', text: 'We build the full valuation analysis: trading comps, precedent transactions, and DCF. We calibrate each with stage-specific multiples, and where applicable, DCF.', output: 'Value range matrix with sensitivity analysis' },
      { step: 'Cap Table & Dilution Analysis', day: 'Day 9–10', text: 'We model your cap table, run your round at multiple valuations, and stress-test dilution at different round sizes. Show the impact on founder equity.', output: 'Post-round cap table and dilution waterfall scenarios' },
      { step: 'Negotiation Preparation', day: 'Day 11–12', text: 'We prepare you for the negotiation: your valuation case, your defence, how to manage counter-offers, and how to run an NDA process efficiently.', output: 'Negotiation talking points and defence playbook (PDF)' },
    ],
    pricingNote: STANDARD_PRICING_NOTE,
    finalCta: {
      title: 'Ready to Defend Your Valuation?',
      description: 'Book a 30-minute scoping call. We will frame the right valuation approach for your raise.',
      cta: { label: 'Get Started', to: '/contact' },
    },
    faqs: [
      { q: 'Will VCs actually accept your valuation?', a: 'Investors will always negotiate. Our memos hold up under diligence and equip you to defend a strong number with evidence.' },
      { q: 'Which sectors do you cover?', a: 'SaaS, fintech, marketplaces, healthtech, deeptech, climate, and consumer. We engage where we have direct experience.' },
      { q: 'How fast can you turn this around?', a: 'Standard 2 weeks. Rush turnarounds available for time-sensitive negotiations.' },
      { q: 'Can you join the investor call to defend the number?', a: 'On request, and depending on stage. Many founders ask us to prep them rather than join — both work.' },
    ],
  },
  {
    slug: 'investor-outreach',
    title: 'Investor Outreach',
    tagline: 'The right investor, at the right time.',
    accent: 'turquoise',
    why: 'Strategic, targeted investor outreach built on thesis alignment, stage fit, and sector expertise — paired with warm introductions from our established network across North America and Europe.',
    whyHeading: 'A sharp pipeline beats a broad blast every time.',
    pricing: [
      {
        tier: 'Targeting & Strategy',
        price: '$1,400',
        sub: 'For founders who need a curated target list and outreach strategy — execution not included.',
        popular: false,
        features: [
          'Curated long list (50–75 firms), prioritised by fit',
          'Fund summary doc (for each 5)',
          'Tier segmentation (priority / secondary / long-list)',
          'Personalised email sequences (3 emails per investor)',
          'Warm introduction (3 per week)',
          '60-min strategy session',
        ],
        cta: 'Get Started',
      },
      {
        tier: 'Full Outreach Program',
        price: '$3,000',
        sub: 'The complete investor outreach — from targeting to introductions to pipeline management.',
        popular: true,
        features: [
          'Everything in Targeting & Strategy',
          'Full investor long-list (75–150 investors)',
          'Warm introductions via our network',
          'Personalised email sequences for each investor',
          'Personalised social outreach (LinkedIn + email)',
          'Campaign launch and co-ordination',
          'Pipeline launch and 180 responses',
          'In-week pipeline management and investor co-ordination',
          'Weekly status report and action alignment',
          'Post-closing follow-up and close-out report',
        ],
        cta: 'Get Started',
      },
      {
        tier: 'Dedicated Program',
        price: 'Custom',
        sub: 'For founders who want an active, senior day-to-day co-pilot on investor relations for the full raise.',
        popular: false,
        features: [
          'Content investor mapping',
          'Daily/weekly investor tracking and management',
          'Warm intro, multiple rounds',
          'Investor deck review',
          'Contact investor, multiple sectors',
          'Investor relationship management',
          'Post-close follow-up and close-out',
          'Priority response within 24 hours',
        ],
        cta: 'Get Started',
      },
    ],
    whatsIncluded: [
      'Curated long list (up to 150 firms) reviewed against your stage, sector, geography',
      'Tier segmentation (priority / secondary / long-list)',
      'Introduction pathway: introduction route vs. cold outreach',
      'Investor one-pager / teaser format (used for outreach)',
      'Personalised email sequences for each investor',
      'Warm network via our North America and Europe connections',
      'Outreach launch coordination (100M+ investors)',
      'Investor one-page / teaser newsletter for outreach',
      'Follow-up cadence management (each 1-week per campaign)',
      'Weekly pipeline status report and action alignment',
      'Post-meeting material and ideas (and quick questions)',
      'Post-closing follow-up and investor feedback synthesis',
    ],
    whyPoints: [
      {
        title: 'Spray-and-Pray Burns Your Reputation',
        text: 'Cold outreach to dozens of mismatched funds signals desperation and damages your standing in tight investor communities.',
      },
      {
        title: 'Thesis-Fit Beats Volume',
        text: '20 investors with active thesis alignment will close your round faster than 200 random intros. Targeting is leverage.',
      },
      {
        title: 'Warm Beats Cold — Always',
        text: 'A warm introduction from a credible source is worth ten cold emails. Network access is what separates founders who close from those who chase.',
      },
    ],
    deliverHeading: 'Targeted outreach designed to convert — not just to generate noise.',
    deliver: [
      { title: 'Thesis-Aligned Targeting', text: 'A curated investor universe of 50–100 funds, scored on thesis fit, stage fit, sector focus, and warmth of relationship.' },
      { title: 'Warm Introduction Network', text: 'Direct, warm introductions to investors where we have an established relationship and the fit is real.' },
      { title: 'North America & Europe Coverage', text: 'Active investor relationships in both geographies — and the context to navigate the differences in investor expectations.' },
      { title: 'Tailored Outreach Materials', text: 'Outreach copy, follow-up sequencing, and supporting one-pagers tailored to each investor archetype.' },
      { title: 'Pipeline Management', text: 'A structured process for tracking responses, managing diligence requests, and maintaining momentum across the full pipeline.' },
      { title: 'Investor Relationship Preparation', text: 'Briefing notes on each investor — fund focus, partner background, recent investments — so you walk into every meeting informed.' },
    ],
    process: [
      { step: 'Investors Targeting & Research', day: 'Day 1–5', text: 'We build a curated, scored investor long-list (50–150 firms). We segment by tier: thesis fit, stage, geography, and likely relationship to introduction.', output: 'Target investor long-list and tier segmentation document' },
      { step: 'Outreach Strategy Design', day: 'Day 6–7', text: 'We design full outreach methodology, timing, and approach. We write and customise outreach copy, personalise for each firm type, and align on campaign launch date.', output: 'Themed outreach strategy document' },
      { step: 'Materials Development', day: 'Day 8–10', text: 'We develop all investor-facing materials for the campaign: one-pager, teaser email, subject lines for each firm type. All materials are reviewed by our team before launch.', output: 'Three investor outreach materials (per target)' },
      { step: 'Introductions & Campaign Launch', day: 'Day 11–15', text: 'We launch the outreach and pipeline tracking. We start introductions via our network, followed by personalised email sequences for each firm.', output: 'Active pipeline with weekly reporting and actions aligned' },
      { step: 'Pipeline Management & Follow-Up', day: 'Ongoing (4–8 weeks)', text: 'We track your investor pipeline, manage follow-ups, and provide co-ordination support throughout the process. Weekly status reports and investor feedback aligned.', output: 'Weekly pipeline status report with each action co-ordinated' },
    ],
    pricingNote: STANDARD_PRICING_NOTE,
    pipelineCta: true,
    finalCta: {
      title: 'Start Building Your Investor Pipeline.',
      description: "Let's map your investor universe and build an outreach strategy designed to convert.",
      cta: { label: 'Book a Free Strategy Call', to: '/contact' },
    },
    faqs: [
      { q: 'Do you guarantee meetings or term sheets?', a: 'No firm guarantees process quality. We commit to the right targeting, warm intros where relevant, and disciplined pipeline management.' },
      { q: 'Can you raise the round for me?', a: 'No. Only the founder can lead a round. Our role is to put you in front of the right investors, fully prepared.' },
      { q: 'What geographies do you cover?', a: 'North America and Europe primarily. Selective engagements in other regions where we have direct relationships.' },
      { q: 'How long is the engagement?', a: 'Typical engagements run 8 weeks of active outreach, with shorter targeted sprints available.' },
    ],
  },
  {
    slug: 'investment-readiness',
    title: 'Investment Readiness',
    tagline: 'Identify gaps before investors do.',
    accent: 'teal',
    why: 'A comprehensive diagnostic of your entire fundraising package — deck, financials, data room, legal structure, and founder narrative — ensuring you present a watertight investment case before you approach a single investor.',
    whyHeading: 'The majority of failed raises are preventable with the right preparation.',
    pricing: [
      {
        tier: 'Essentials Audit',
        price: '$1,500',
        sub: 'For founders who need a fast diagnostic of their core materials before approaching investors.',
        popular: false,
        features: [
          'Pitch deck gap analysis',
          'Financial package review',
          'Written findings report',
          'Top 3 priority action items',
          'Top 3 priority risk items',
          '60-min call and Q&A',
        ],
        cta: 'Get Started',
      },
      {
        tier: 'Full Readiness',
        price: '$3,200',
        sub: 'The complete investment readiness diagnostic for founders preparing to launch their raise with confidence.',
        popular: true,
        features: [
          'Everything in Essentials Audit',
          'Data room completeness audit',
          'Cap table and legal structure report',
          'NR-dimension gap analysis worksheet',
          'Prioritised action plan with investor-impact scoring',
          'Mock investor Q&A session (60 min)',
          '30-day engagement session window',
        ],
        cta: 'Get Started',
      },
      {
        tier: 'Cohort Program',
        price: 'Custom',
        sub: 'For accelerators running readiness diagnostics across a full cohort before demo day.',
        popular: false,
        features: [
          'Accelerator cohort value sets',
          'Anonymised cohort benchmarking',
          'Cohort risk and issue flagging',
          'Cohort-wide NR-dimension analysis integration',
          'Other data acquisition and management',
          'Priority response within 24 hours',
        ],
        cta: 'Get Started',
      },
    ],
    whatsIncluded: [
      'Full fundraising materials collection (deck, financials, data room, cap table)',
      'Pitch deck audit: narrative, gap analysis, and investor-appropriateness',
      'Financial package review (model integrity, unit economics, consistency)',
      'Data room completeness audit with detailed checklist',
      'Live investor-readiness gap analysis with weighted dimensions (6 areas)',
      'Prioritised action plan with investor-impact scoring (30-day CAT)',
      '60-min debrief session from KPI-to-go perspective',
      'Pitch deck review: story integrity and gap analysis',
      'Follow-up action email with revision prioritisation list',
      'Mock investor Q&A session: 60 min',
      'Written gap analysis report (PDF)',
      'Post-improvement check-in review',
    ],
    whyPoints: [
      {
        title: 'Inconsistencies Are Investor Deal-Breakers',
        text: 'When your deck, model, and data room tell different stories, investors lose trust before they even ask a question. Consistency is non-negotiable.',
      },
      {
        title: 'Missing Materials Stall Momentum',
        text: 'Diligence that pauses for missing documents is diligence that quietly dies. Preparedness is what keeps a process moving.',
      },
      {
        title: 'Hard Questions Will Come — Are You Ready?',
        text: 'Founders who can answer the hardest questions cleanly are the ones who close. Readiness Review prepares you for every angle.',
      },
    ],
    deliverHeading: 'A complete audit of your fundraising readiness across six dimensions.',
    deliver: [
      { title: 'Pitch Deck Audit', text: 'Narrative clarity, story structure, investor-appropriateness, and slide-by-slide gap analysis against your target investor profile.' },
      { title: 'Financial Package Review', text: 'Financial model integrity, unit economics strength, projection credibility, and consistency between your deck and your model.' },
      { title: 'Data Room Assessment', text: "Completeness and organisation of your data room against institutional due diligence standards with a detailed checklist of what's missing." },
      { title: 'Legal & Corporate Structure', text: 'Cap table, share structure, IP assignments, and material contracts reviewed for any flag that could complicate or delay a round.' },
      { title: 'Gap Analysis Report', text: 'A prioritised gap-analysis report showing what is investor-ready, what needs work, and what is high-risk before any meetings.' },
      { title: 'Mock Investor Session', text: 'A simulated investor Q&A session designed to surface weaknesses in your story, your numbers, and your readiness — before the real thing.' },
    ],
    process: [
      { step: 'Materials Collection', day: 'Day 1–2', text: 'You share your deck, financial model, data room, cap table, and key documents. NDAs in place from day one.', output: 'Secure document receipt and review checklist' },
      { step: 'Structured Review (6 Dimensions)', day: 'Day 3–8', text: 'Systematic investment evaluation across six readiness dimensions: narrative, financials, data room, legal, team narrative, and investor appropriateness.', output: 'Weighted scoring and dimension-by-dimension analysis document' },
      { step: 'Gap Analysis & Action Plan', day: 'Day 9–10', text: 'We identify the specific gaps across all six dimensions and prioritise by investor-impact, with a clear action plan and timeline to resolve each.', output: 'Prioritised action plan with investor-impact scoring (PDF)' },
      { step: 'Debrief & Roadmap Session', day: 'Day 11', text: 'We walk through every finding in a 60-minute session, discuss the implications, and align on the roadmap for the next 30 days.', output: 'Shared improvement roadmap and next steps' },
      { step: 'Mock Investor Q&A', day: 'Day 14', text: 'A simulated investor session run using the hardest questions your materials are likely to trigger. We surface weak answers and coach through each one.', output: 'Written Q&A prep document' },
      { step: 'Post-Improvement Check-In', day: 'Day 30 (Post)', text: 'After you have made the improvements, we do a second pass to confirm you are investor-ready and clear your materials for outreach.', output: 'Green-light confirmation or next-level findings' },
    ],
    pricingNote: STANDARD_PRICING_NOTE,
    finalCta: {
      title: 'Ready Before You Walk in the Room?',
      description: 'Run the diagnostic before you approach a single investor. Two weeks could save you a quarter of lost momentum.',
      cta: { label: 'Get Started', to: '/contact' },
    },
    faqs: [
      { q: 'How is this different from just reviewing my pitch deck?', a: 'Pitch Deck Review focuses on the deck. Investment Readiness is a full-package audit — deck, model, data room, legal, narrative — all in one engagement.' },
      { q: "What if I don't have all my materials ready yet?", a: 'That is exactly when this engagement is most valuable. We will work with what you have and tell you precisely what to build before going out.' },
      { q: 'Do you help fix the gaps you identify, or just flag them?', a: 'Both. The diagnostic surfaces gaps. We can remediate the highest-risk items directly via our other services or as ad-hoc advisory.' },
      { q: 'Is this appropriate for first-time founders?', a: 'Especially for first-time founders. The diagnostic gives you a clear, written roadmap to investor-ready, with no guesswork.' },
      { q: 'Can accelerators use this as a pre-demo-day program?', a: 'Yes. We run cohort-format Investment Readiness diagnostics for several accelerator partners across North America and Europe.' },
    ],
  },
  {
    slug: 'ama-sessions',
    title: 'AMA Sessions',
    tagline: "Ask the questions you can't afford to get wrong.",
    accent: 'yellow',
    why: 'Structured one-on-one advisory sessions with experienced venture investors and startup operators. Bring any challenge, any question — and get direct, unfiltered answers from people who have lived the fundraising journey from both sides of the table.',
    whyHeading: "Sometimes you don't need a full engagement. You need one hour with the right person.",
    pricing: [
      {
        tier: 'Single Session',
        price: '$450',
        sub: 'One focused advisory session on any pressing question, decision, or challenge.',
        popular: false,
        features: [
          'Pre-session context review (30 min)',
          'Contextual 60-min advisory session',
          'Written session notes',
          '48-hour follow-up questions',
          'Optional session recording',
        ],
        cta: 'Get Started',
      },
      {
        tier: 'Session Bundle',
        price: '$1,100',
        sub: 'Three sessions across your entire raise — ongoing advisory access when you need it most.',
        popular: true,
        features: [
          'Everything in Single Session × 3',
          'Summary of key 60-min advisory sessions',
          'Session notes and action items',
          'Priority booking (within 48 hours)',
          'Async email thread between sessions',
          'As many sessions as at start of each follow-in session',
        ],
        cta: 'Get Started',
      },
      {
        tier: 'Monthly Advisory',
        price: '$1,800 /mo',
        sub: 'For founders who want a trusted advisor available across the full fundraise journey.',
        popular: false,
        features: [
          '4 × 60-minute sessions per month',
          'Unlimited async email access',
          'Pre-meeting materials briefing, results reviewed',
          'Term sheet and deal term review',
          'Contact-level follow-up',
          'Monthly review',
          'Priority responded within 24 hours',
        ],
        cta: 'Get Started',
      },
    ],
    whatsIncluded: [
      'Pre-session context review by the advisor (your deck, model, or specific context shared)',
      'Real-time feedback and coaching during the session',
      'All-in-one focused advisory session with an experienced operator and investor',
      'Written session notes delivered after the session',
      'Written action points summary (delivered next business day)',
      '48-hour follow-up window for any immediate post-session questions',
      'Optional session recording for your reference (on request)',
    ],
    whyPoints: [
      {
        title: 'Generic Advice Is Everywhere — Specific Advice Is Rare',
        text: 'Blog posts and articles give you frameworks. An AMA session gives you advice calibrated to your stage, your team, and your specific situation.',
      },
      {
        title: "The Questions You Don't Know to Ask Are the Most Dangerous",
        text: 'Experienced investors surface the risks and decisions you would not have spotted yourself. Outside perspective changes outcomes.',
      },
      {
        title: 'Fast Access to Expertise Changes Outcomes',
        text: 'Founders who get the right feedback before a critical decision close better rounds, sign better terms, and avoid avoidable mistakes.',
      },
    ],
    deliverHeading: 'Direct, actionable answers from experienced operators and investors.',
    deliver: [
      { title: 'Investor-Perspective Feedback', text: 'Our advisors have evaluated hundreds of deals from the investor seat. They tell you what a VC is actually thinking — not what you want to hear.' },
      { title: 'Fundraise Strategy Guidance', text: "Round sizing, valuation anchoring, sequencing, timing, term sheet navigation — whatever aspect of your fundraise you're wrestling with." },
      { title: 'Pitch and Narrative Coaching', text: "Real-time feedback on how you're presenting your story — what's working, what's confusing, what's losing investor attention." },
      { title: 'Materials Spot Review', text: 'Share a specific slide, a financial assumption, or a section of your deck and get direct feedback in the session.' },
      { title: 'Investor Relationship Advice', text: "Navigating specific investor dynamics, follow-up strategy, managing multiple processes simultaneously — we've been in these situations." },
      { title: 'Next-Day Session Notes', text: 'Written summary of key discussion points and recommended next steps delivered the following business day.' },
    ],
    process: [
      { step: 'Pre-Session Brief', day: '24h before', text: 'You share a short brief on your situation, the questions you want to cover, and any materials for review. We prepare specifically for your context.', output: 'Preparation notes and specific question framework' },
      { step: 'Structured 60-Minute Session', day: 'Session day', text: 'A focused working session with a senior partner that works through your questions and challenges. We make sure to right-first-time on your most important questions.', output: 'Session notes, clarifications, and next-right options' },
      { step: 'Session Notes & Action Items', day: 'Next business day', text: 'Written summary of all key discussion points, recommended next steps, and open items to follow up on. Delivered the following business day (PDF).', output: 'Written session summary (PDF)' },
      { step: 'All-Hour Follow-Up Window', day: '5 days after the call', text: 'Light follow-up access for 48 hours after the session to address any immediate questions or clarifications that come up as you start implementing.', output: 'Prioritised responses as you put together your session plan' },
    ],
    pricingNote: STANDARD_PRICING_NOTE,
    finalCta: {
      title: 'Ready to Get the Answer You Need?',
      description: 'Book a single AMA session or a pack of four. Both start with a free 15-minute fit call.',
      cta: { label: 'Book a Session', to: '/contact' },
    },
    faqs: [
      { q: 'What kinds of questions are best suited for an AMA session?', a: 'Anything tactical and time-sensitive: round sizing, term sheet review, valuation anchoring, investor relationship dynamics, deck or model spot-review.' },
      { q: 'Do I need to have a specific problem, or can I use it more generally?', a: 'Both work. Many founders use AMA for a specific decision; others book a pack of four to use across a quarter as questions arise.' },
      { q: 'How quickly can I book a session?', a: 'Standard availability is within 5 business days. Same-week and next-day availability is often possible for time-sensitive situations.' },
      { q: 'Who specifically will I be talking to?', a: 'A senior partner with direct VC and operator experience — not a generalist advisor.' },
      { q: 'Can I share materials in advance for the advisor to review?', a: 'Yes. Sharing materials 24 hours in advance lets us prepare and makes the session more productive.' },
      { q: 'Is this confidential?', a: 'Absolutely. Mutual NDAs are standard. Nothing discussed in the session is shared outside the engagement.' },
    ],
  },
];

export const ARTICLES = [
  {
    slug: 'ten-things-investors-look-for',
    category: 'Pitch Deck',
    readTime: '8 min read',
    date: 'April 12, 2026',
    title:
      'The 10 Things Every Investor Looks for in a Pitch Deck (and Where Most Founders Fall Short)',
    excerpt:
      'After evaluating thousands of early-stage decks, patterns emerge quickly. Here are the exact criteria institutional investors apply and the most common places founders lose the room.',
    accent: 'yellow',
  },
  {
    slug: 'why-financial-model-rejected',
    category: 'Financial Model',
    readTime: '7 min read',
    date: 'March 28, 2026',
    title: 'Why Your Financial Model Gets Rejected (Even When the Business is Strong)',
    excerpt:
      "A weak financial model doesn't just lose you credibility on the numbers — it signals a fundamental gap in how a founder understands their own business. Here's how to fix it before you walk into a meeting.",
    accent: 'turquoise',
  },
  {
    slug: 'anchor-pre-money-valuation',
    category: 'Valuation',
    readTime: '6 min read',
    date: 'March 14, 2026',
    title: 'How to Anchor Your Pre-Money Valuation Without Guessing',
    excerpt:
      'Early-stage valuation is part analysis, part negotiation, and part conviction. Here is the framework we use to triangulate a defensible number.',
    accent: 'teal',
  },
];

export const FEATURED_DOWNLOADS = [
  {
    label: 'Spreadsheet template',
    title: 'Investor-Grade Financial Model',
    cta: 'Download (Google Sheets)',
    accent: 'yellow',
  },
  {
    label: 'Slide template',
    title: 'Pitch Deck Skeleton',
    cta: 'Download (Google Slides)',
    accent: 'turquoise',
  },
   {
    label: 'Finance',
    title: 'Burn Runaway Modeler',
    cta: 'Plug in your expense and MRR, see your runway instantly.Know when to fundraise before its too late.',
    accent: 'turquoise',
    route:'/burnrunway',
  }, {
    label: 'Growth',
    title: 'Revenue Projector',
    cta: 'Model month-on-month growth scenerio.Bull,bear and base cases.',
    accent: 'yellow',
    route: '/revenueprojector',
  }, {
    label: 'Fundraising',
    title: 'SAFE dilution Modeler',
    cta: 'Stack multiple SAFE rounds, see dilution impact before your priced round. Know what you are giving away before you sign the term sheet. ',
    accent: 'yellow',
    route: '/safedilution',
  },
];

export const INVESTOR_PIPELINE_CTA = {
  title: 'Start Building Your Investor Pipeline.',
  description:
    "Let's map your investor universe and build an outreach strategy designed to convert.",
  cta: { label: 'Book a Free Strategy Call', to: '/contact' },
  note: 'No obligation. 30 minutes. All new engagements start here.',
};

export const SERVICE_BY_SLUG = Object.fromEntries(SERVICES.map((s) => [s.slug, s]));